USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON PROAGENTE_IMOBILIARIO
REBUILD;
ALTER INDEX ALL ON PROALBUM
REBUILD;
ALTER INDEX ALL ON PROCIDAD
REBUILD;
ALTER INDEX ALL ON PROCONTC
REBUILD;
ALTER INDEX ALL ON PROPAIS
REBUILD;
ALTER INDEX ALL ON PROPROPR
REBUILD;
GO