import { computed } from 'vue'

export default class MapResources
{
	constructor(fnGetResource)
	{
		this._fnGetResource = typeof fnGetResource !== 'function' ? resId => resId : fnGetResource
		Object.defineProperty(this, '_fnGetResource', { enumerable: false })

		this.search = computed(() => this._fnGetResource('PESQUISAR34506'))
		this.defaultLayer = computed(() => this._fnGetResource('CAMADA_PADRAO16799'))
		this.clusterGroupLayer = computed(() => this._fnGetResource('CAMADA_DE_GRUPO23322'))
		this.shapesLayer = computed(() => this._fnGetResource('CAMADA_DE_FORMAS24489'))
		this.latitude = computed(() => this._fnGetResource('LATITUDE11291'))
		this.longitude = computed(() => this._fnGetResource('LONGITUDE01015'))
		this.description = computed(() => this._fnGetResource('DESCRICAO_19279'))
		this.cancel = computed(() => this._fnGetResource('CANCELAR49513'))
		this.finish = computed(() => this._fnGetResource('TERMINAR61258'))
		this.deleteLastPoint = computed(() => this._fnGetResource('EXCLUIR_ULTIMO_PONTO23497'))
		this.drawPolyline = computed(() => this._fnGetResource('DESENHAR_UMA_POLILIN61896'))
		this.drawPolygon = computed(() => this._fnGetResource('DESENHAR_UM_POLIGONO12868'))
		this.drawRectangle = computed(() => this._fnGetResource('DESENHAR_UM_RETANGUL46722'))
		this.drawCircle = computed(() => this._fnGetResource('DESENHAR_UM_CIRCULO51276'))
		this.drawMarker = computed(() => this._fnGetResource('DESENHAR_UM_MARCADOR25870'))
		this.drawCircleMarker = computed(() => this._fnGetResource('DESENHAR_UM_MARCADOR34224'))
		this.drawText = computed(() => this._fnGetResource('DESENHAR_TEXTO17458'))
		this.radius = computed(() => this._fnGetResource('RAIO02224'))
		this.area = computed(() => this._fnGetResource('AREA19058'))
		this.perimeter = computed(() => this._fnGetResource('PERIMETRO27301'))
		this.startCircleDraw = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_36879'))
		this.endCircleDraw = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_12531'))
		this.placeCircleMarker = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_01379'))
		this.placeMarker = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_27665'))
		this.placeText = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_49809'))
		this.startShapeDraw = computed(() => this._fnGetResource('CLIQUE_PARA_COMECAR_46982'))
		this.continueShapeDraw = computed(() => this._fnGetResource('CLIQUE_PARA_CONTINUA55696'))
		this.endShapeDraw = computed(() => this._fnGetResource('CLIQUE_NO_PRIMEIRO_P63933'))
		this.endLineDraw = computed(() => this._fnGetResource('CLIQUE_NO_ULTIMO_PON17740'))
		this.endDrawing = computed(() => this._fnGetResource('CLIQUE_NO_MAPA_PARA_15804'))
		this.editLayers = computed(() => this._fnGetResource('EDITAR_CAMADAS13617'))
		this.deleteLayers = computed(() => this._fnGetResource('EXCLUIR_CAMADAS60432'))
		this.dragLayers = computed(() => this._fnGetResource('ARRASTAR_CAMADAS24431'))
		this.cutLayers = computed(() => this._fnGetResource('RECORTAR_CAMADAS43897'))
		this.rotateLayers = computed(() => this._fnGetResource('RODAR_CAMADAS32297'))
		this.scaleLayers = computed(() => this._fnGetResource('REDIMENSIONAR_CAMADA64500'))
		this.snapVertices = computed(() => this._fnGetResource('JUNTAR_O_MARCADOR_AR20474'))
		this.pinVertices = computed(() => this._fnGetResource('PRENDER_OS_VERTICES_56161'))
		this.autoTrace = computed(() => this._fnGetResource('DETETAR_LINHA_AUTOMA12070'))
		this.length = computed(() => this._fnGetResource('COMPRIMENTO42533'))
		this.segmentLength = computed(() => this._fnGetResource('COMPRIMENTO_DO_SEGME01997'))
		this.height = computed(() => this._fnGetResource('ALTURA57630'))
		this.width = computed(() => this._fnGetResource('LARGURA03667'))
		this.position = computed(() => this._fnGetResource('POSICAO07486'))
		this.positionMarker = computed(() => this._fnGetResource('MARCADOR_DA_POSICAO09118'))
		this.externalLayer = computed(() => this._fnGetResource('CAMADA_EXTERNA30603'))
		this.printMap = computed(() => this._fnGetResource('IMPRIMIR_MAPA10717'))
		this.printLandscape = computed(() => this._fnGetResource('PAISAGEM06194'))
		this.printPortrait = computed(() => this._fnGetResource('RETRATO07729'))
	}
}
